// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3B_ClbXEKni-mQdkm1q4ogyCPvvKjec',
    appId: '1:305727623385:web:66102e58eb15eb2b186ec8',
    messagingSenderId: '305727623385',
    projectId: 'messy-flea-market',
    authDomain: 'messy-flea-market.firebaseapp.com',
    storageBucket: 'messy-flea-market.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIUdiY_FlpwNgdkbcvsg3d15G-fj7yU4c',
    appId: '1:305727623385:android:c7ea010d7d6eb267186ec8',
    messagingSenderId: '305727623385',
    projectId: 'messy-flea-market',
    storageBucket: 'messy-flea-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ6kmzFGD__9SWv1-esMGO0x1_rGUFz6w',
    appId: '1:305727623385:ios:45eab6a7c0705308186ec8',
    messagingSenderId: '305727623385',
    projectId: 'messy-flea-market',
    storageBucket: 'messy-flea-market.firebasestorage.app',
    iosClientId: '305727623385-qbjdmv31v0ejfmv1pomfe28q6p190ob4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasicVenture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ6kmzFGD__9SWv1-esMGO0x1_rGUFz6w',
    appId: '1:305727623385:ios:45eab6a7c0705308186ec8',
    messagingSenderId: '305727623385',
    projectId: 'messy-flea-market',
    storageBucket: 'messy-flea-market.firebasestorage.app',
    iosClientId: '305727623385-qbjdmv31v0ejfmv1pomfe28q6p190ob4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBasicVenture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ3B_ClbXEKni-mQdkm1q4ogyCPvvKjec',
    appId: '1:305727623385:web:a1c5da4ca3fb2f43186ec8',
    messagingSenderId: '305727623385',
    projectId: 'messy-flea-market',
    authDomain: 'messy-flea-market.firebaseapp.com',
    storageBucket: 'messy-flea-market.firebasestorage.app',
  );
}
